import Layout from "@/components/layout/Layout";
import Head from "next/head";

const about = () => {
  return (
    <>
      <Head>
        <title>about</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h3>About</h3>
      </Layout>
    </>
  );
};

export default about;
