import AboutDetails from "@/components/about/AboutDetails";
import AboutExperience from "@/components/about/AboutExperience";
import AboutHero from "@/components/about/AboutHero";
import Layout from "@/components/layout/Layout";
import Head from "next/head";

const about = () => {
  return (
    <>
      <Head>
        <title>about</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <AboutHero />
        <AboutDetails />
        <AboutExperience />
      </Layout>
    </>
  );
};

export default about;
