import AboutDetails from "@/components/about/AboutDetails";
import AboutExperience from "@/components/about/AboutExperience";
import AboutHero from "@/components/about/AboutHero";
import ExploreShiekhSlider from "@/components/about/ExploreShiekhSlider";
import Layout from "@/components/layout/Layout";
import Head from "next/head";

const about = () => {
  return (
    <>
      <Head>
        <title>about</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          type="text/css"
          charset="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </Head>
      <Layout>
        <AboutHero />
        <AboutDetails />
        <AboutExperience />
        <ExploreShiekhSlider />
      </Layout>
    </>
  );
};

export default about;
